version: "3"

services:
    
  nginx:
    image: nginx:1.14.0
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/war/www/app/web
#      - /var/run/php/php7.2-fpm.sock:/var/run/php/php7.2-fpm.sock

#  apache:
#    image: httpd
#    ports:
#      - 88:80
#    volumes:
#      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
#      - ./web:/war/www/app/web
##      - /var/run/php/php7.2-fpm.sock:/var/run/php/php7.2-fpm.sock

  php:
    build:
      ./docker/php
    volumes:
      - ./:/war/www/app
    working_dir: /war/www/app
    user: "1000:1000"

  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
      #redis-data #фаловая система создется docker-ом
    command: 'redis-server --appendonly yes'

  mongo:
    image: mongo:3.6.3
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

  postgres:
    image: postgres:10.12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB:postgres_db
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:password
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7.30
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    volumes:
      - ./mysql-data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: 12345
#      MYSQL_ROOT_PASSWORD: root
#
##volumes:
#    #redis-data: #фаловая система создется docker-ом
#    #mongo-data:
#    #pg-data: